# Generated by Django 6.0.6 on 2026-07-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_estimated_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='outcomes',
            field=models.JSONField(blank=True, default=list, help_text='List of learning outcomes (strings)'),
        ),
    ]
